name = "lean4lean"
defaultTargets = ["Lean4Lean", "lean4lean", "Lean4Lean.Theory", "Lean4Lean.Verify"]

[[require]]
name = "batteries"
git = "https://github.com/leanprover-community/batteries"
rev = "v4.27.0-rc1"

[[require]]
scope = "leanprover"
name = "lean4export"
rev = "joachim_parse_fixes"

[[lean_lib]]
name = "Lean4Lean"

[[lean_lib]]
name = "Lean4Lean.Theory"
globs = ["Lean4Lean.Theory.*"]

[[lean_lib]]
name = "Lean4Lean.Verify"
globs = ["Lean4Lean.Verify.*"]

[[lean_lib]]
name = "Lean4Lean.Experimental"
globs = ["Lean4Lean.Experimental.+"]

[[lean_exe]]
name = "lean4lean"
root = "Main"
supportInterpreter = true
